//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordStorage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordStorage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your file....
        /// </summary>
        internal static string BrowseDialogHeader {
            get {
                return ResourceManager.GetString("BrowseDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pwd.
        /// </summary>
        internal static string BrowseFilterExtension {
            get {
                return ResourceManager.GetString("BrowseFilterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password files.
        /// </summary>
        internal static string BrowseFilterName {
            get {
                return ResourceManager.GetString("BrowseFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Apply.
        /// </summary>
        internal static string ButtonApplyFilterText {
            get {
                return ResourceManager.GetString("ButtonApplyFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse....
        /// </summary>
        internal static string ButtonBrowseText {
            get {
                return ResourceManager.GetString("ButtonBrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &amp;Login.
        /// </summary>
        internal static string ButtonCopyLoginText {
            get {
                return ResourceManager.GetString("ButtonCopyLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &amp;Password.
        /// </summary>
        internal static string ButtonCopyPaswordText {
            get {
                return ResourceManager.GetString("ButtonCopyPaswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&amp;oad.
        /// </summary>
        internal static string ButtonLoadText {
            get {
                return ResourceManager.GetString("ButtonLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string ButtonSaveText {
            get {
                return ResourceManager.GetString("ButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with passwords.
        /// </summary>
        internal static string GroupBoxFileHeader {
            get {
                return ResourceManager.GetString("GroupBoxFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string GroupBoxFilterHeader {
            get {
                return ResourceManager.GetString("GroupBoxFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        internal static string GroupBoxPasswordsHeader {
            get {
                return ResourceManager.GetString("GroupBoxPasswordsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items filtered. Saving will delete them. Do you wont continue?.
        /// </summary>
        internal static string ItemsFilteredWarning {
            get {
                return ResourceManager.GetString("ItemsFilteredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may lost a data.
        /// </summary>
        internal static string MayLostDataCaption {
            get {
                return ResourceManager.GetString("MayLostDataCaption", resourceCulture);
            }
        }
    }
}
